Enhance linting targets

diff --git a/Makefile.lint b/Makefile.lint
--- a/Makefile.lint
+++ b/Makefile.lint
@@ -11,8 +11,17 @@ endif
 # Default configuration
 # -------------------------------------------------------------------------------------------------
 CURRENT_DIR = $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
+# File lint
 FL_VERSION  = 0.4
-FL_IGNORES  = .git/,.github/,tests/
+FL_IGNORES  = .git/,.github/
+# Json lint
+JL_VERSION = 1.6.0-0.5
+JL_IGNORES = .git/,.github/
+# Yamllint
+YL_VERSION = 1.26-0.9
+# Shellcheck
+SC_IGNORES = .git/,.github/
+SC_VERSION = stable
 
 
 # -------------------------------------------------------------------------------------------------
@@ -21,6 +30,8 @@ FL_IGNORES  = .git/,.github/,tests/
 .PHONY: lint
 lint: lint-files
 lint: lint-yaml
+lint: lint-json
+lint: lint-bash
 
 
 .PHONY: lint-files
@@ -39,9 +50,44 @@ lint-files:
 
 .PHONY: lint-yaml
 lint-yaml:
-	@# Lint all files
 	@echo "################################################################################"
 	@echo "# Lint Yaml"
 	@echo "################################################################################"
-	@docker run --rm $$(tty -s && echo "-it" || echo) -v $(CURRENT_DIR):/data cytopia/yamllint .
+	@if docker run --rm $$(tty -s && echo "-it" || echo) -v "$(CURRENT_DIR):/data:ro" -w /data cytopia/yamllint:$(YL_VERSION) .; then \
+		echo "OK"; \
+	else \
+		echo "Failed"; \
+		exit 1; \
+	fi;
 	@echo
+
+
+.PHONY: lint-json
+lint-json:
+	@echo "################################################################################"
+	@echo "# Lint JSON"
+	@echo "################################################################################"
+	@if docker run --rm $$(tty -s && echo "-it" || echo) -v "$(CURRENT_DIR):/data:ro" -w /data cytopia/jsonlint:$(JL_VERSION) \
+		-t '  ' -i '$(JL_IGNORES)' '*.json'; then \
+		echo "OK"; \
+	else \
+		echo "Failed"; \
+		exit 1; \
+	fi;
+	@echo
+
+
+.PHONY: lint-bash
+lint-bash:
+	@echo "################################################################################"
+	@echo "# Lint Bash"
+	@echo "################################################################################"
+	@IGNORES=""; \
+	if [ "$(SC_IGNORES)" ]; then \
+		IGNORES="$$( echo "-not \( -path \"./$(SC_IGNORES)*\"" | sed 's|,|*" -o -path "./|g' ) \)"; \
+	fi; \
+	CMD="find . -name '*.sh' $${IGNORES} -print0"; \
+	echo "$${CMD}"; \
+	if [ "$$( eval "$${CMD}" )" != "" ]; then \
+		eval "$${CMD}" | xargs -0 -n1  docker run --rm -v $(CURRENT_DIR):/data -w /data koalaman/shellcheck:$(SC_VERSION) --shell=bash; \
+	fi
